---
title: "Assignment 2"
author: "Stefano Graziosi, Gabriele Molè, Laura Loschiavo, Giovanni Carron"
format: html
editor: visual
---

### Set-up

```{r echo = "FALSE"}
#| label: Load the relevant libraries

# To solve conflicts
library(conflicted)
conflicts_prefer(dplyr::filter)

# Time series packages
library(dlm)
library(TSstudio)
library(feasts)
library(tseries)
  # Necessary packages for quantmod
  library(zoo)
  library(xts)
library(quantmod)

#Specifically for Assignment 2
library(depmixS4)
library(HiddenMarkov)

# Datasets
library(readr)
library(fpp3)

# For fancy plots
library(ggthemes)
  # Necessary packages for viridis
  library(viridisLite)
library(viridis)
library(gridExtra)
library(magrittr)
library(textab)

# Packages related to tidyverse, for data manipulation
library(tidyverse) # includes (lubridate), (dplyr), (ggplot2), (tidyr), (tidyselect)
library(tinytex)

# To handle time changes
library(timechange)
```

```{r}
#| label: Loading the dataset

# Importing the data
urlfile = "https://raw.githubusercontent.com/stfgrz/20236-timeseries-ps/97a64d30e6a67339343f36fba4ac9bb9ad75dd7e/ps2/data_assHMM.csv"
data<-read_csv(url(urlfile))

# Getting the nominal data
nom_int_data <- data[, 2] 
ts_data_nom <- ts(as.vector(t(nom_int_data)), start = c(1997, 1), frequency = 12)
```


```{r}
? depmixS4
```

```{r}
? lm
```

```{r}
? glm
```

```{r}
? depmix
```

```{r}
? posterior
```

# 2. Hidden Markov Models

## 2.1 Part (a)

## 2.2 Part (b)




